# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e58cabffd35218491f890e0491b148c6d18f8c47b2c610798652ce1b6ae32db2e1b45bea1a6fe933da685504546cb93ae3493363ef452c30b02f25a99af92bf

test:
  secret_key_base: 78f9963bf869648b2fb7a0a3a16e80066345ab551eb98119c533f0dab79471cd83059f1202f3aae270694fd93dd9786949d815ebc8f7a191f92dc60abd2a4ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
